url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "Capstone-Project" # the subpath of your site, e.g. /blog
title: "Capstone Portfolio" # the name of your site, e.g. ACME Corp.
